### ISSUE TITLE
Panic on Following locked account

### ISSUE THREAD

**Issue by shleeable** [tootsuite/flodgatt#114]
Easily replicatable.. try to follow a locked account and boom

`[36mflodgatt_1  |[0m thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unknown variant `follow_request`, expected one of `follow`, `mention`, `reblog`, `favourite`, `poll`", line: 0, column: 0)', src/redis_to_client_stream/redis/redis_msg.rs:53:36`

<img width="1606" alt="image" src="https://user-images.githubusercontent.com/17537000/78100952-8f462f00-7418-11ea-9f91-d561edb9201e.png">

lol.. pointless backtrace

**Comment by codesections** [comment]
Fixed in #115
