### ISSUE TITLE
Add additional configuration variables 

### ISSUE THREAD

**Issue by codesections** [tootsuite/flodgatt#23]
We should configuration options to match the configuration options in tootsuite/mastodon, as described in [the documentation](https://docs.joinmastodon.org/administration/configuration/).

Specifically, we should add the following variables:

**PostgreSQL**
- [x] DB_HOST
- [x] DB_USER
- [x] DB_NAME
- [x] DB_PASS
- [x] DB_PORT
- [x] DATABASE_URL
- [x] DB_SSLMODE

**Redis**
- [x] REDIS_HOST
- [x] REDIS_PORT
- [x] REDIS_URL
- [x] REDIS_DB
- [x] REDIS_NAMESPACE
- [x] REDIS_PASSWORD

**Deployment**

- [x] PORT
- [x] SOCKET
- [x] BIND
- [x] RUST_ENV / NODE_ENV
- [x] RUST_LOG_LEVEL
- [ ] TRUSTED_PROXY_IP

Are there any others that we should also add?

[EDIT: We should also remove `.env` from version control (though we could have a example config).  When doing so, it might also make sense to switch from `pretty_env_logger` to `env_logger`, which has essentially the same API and would let us set the default log level without an env variable.]

**Comment by Gargron** [comment]
- LOG_LEVEL
- SOCKET (for binding to Unix socket instead of TCP interface)
- BIND (for choosing TCP interface)
- DB_SSLMODE
- TRUSTED_PROXY_IP (which source IP to trust for forwarded IP info)
- REDIS_DB
- REDIS_PASSWORD

**Comment by codesections** [comment]
We also need to add an environmental variable that specifies what other environmental variables to use.  `flodgatt` should read the other env vars from a `.env` file with that post-fix.  For example, if the variable is set to `development`, flodgatt should read other variables from `.env.production`.

The user should be able to set this variable as `NODE_ENV` (for backwards compatibility) or as `RUST_ENV` (to be clearer).  If both are set, `RUST_ENV` should take precedence.

**Comment by codesections** [comment]
Closing this for now.  Depending on how Mastodon ends up handling `TRUSTED_PROXY_IP`, we may want to reopen later.  Also, we currently support `DB_SSLMODE` only in that we acknowledge it and print a warning that we don't yet support using SSL with Postgres (#41).  When we add SSL support, we'll obviously need to expand our handling of that environmental variable.
