### ISSUE TITLE
Create binary release [update: staticly linked]

### ISSUE THREAD

**Issue by codesections** [tootsuite/flodgatt#39]

**Comment by codesections** [comment]
As of 0.3.0, flodgatt has a binary release.  However, I'm leaving this issue open because it is not yet a statically linked binary.  It is only dynamically linked to some fairly common system libraries (most noteably, `open_ssl`, so it *should* work on most Linux distros.  But I've only tested it on Debian stable and it would be nice to have a staticly linked only binary without any dependencies.

**Comment by Shleeble** [comment]
Just an FYI... this looks fine from our docker setup but openssl isn't linked?

```
mastodon@5146f0176373:~$ ldd flodgatt
	linux-vdso.so.1 (0x00007ffc3ed8d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3ebf34f000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3ebf147000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3ebef28000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3ebed10000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3ebe91f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3ebfaa3000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3ebe581000)
```

**Comment by codesections** [comment]
Closed because linking against musl isn't needed
